version: '3.8'
services:
  mongodb:
    image: mongo:6
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  web:
    build: .
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB_NAME=LogisticsDB
      - SECRET_KEY=super-secret-key
    ports:
      - "5000:5000"
    volumes:
      - .:/app